### ISSUE TITLE
Revamp Demo Application

### ISSUE THREAD

**Issue by VictorKaycee17** [DeCenter-AI/decenterai-demo.streamlit#1]
Revamp the Streamlit demo to follow these steps

- Visit https://decenter-ai.streamlit.app/
- Enter model name
- Upload training dataset
- Select training script
- Click train
- Model training commences
- After training is done , you can download your trained model

![Image](https://github.com/DeCenter-AI/decenterai-demo.streamlit.app/assets/131058062/7732e5fd-911d-4986-a691-0989f1bda014)

- [x] Remove the side bar from appearing at default when a user visits the demo

![Image](https://github.com/DeCenter-AI/decenterai-demo.streamlit.app/assets/131058062/f9bf34d4-f4cc-490a-b1a2-9781083d36f9)

- [x] Remove the Version section and the demo section

![Image](https://github.com/DeCenter-AI/decenterai-demo.streamlit.app/assets/131058062/d3da1970-56bc-438d-bf8f-e5bf2c06750f)

- [x] The model name box should say "Enter Model Name" by default and should be editable

![Image](https://github.com/DeCenter-AI/decenterai-demo.streamlit.app/assets/131058062/a3395b2e-69a2-4cce-9a89-c3614b56f884)

- [x] The Training script Box should be empty by default until the user clicks the dropdown button so select a training script

![Image](https://github.com/DeCenter-AI/decenterai-demo.streamlit.app/assets/131058062/e818a605-a29f-4fef-a664-5644705f365d)

- [x] Please remove these, They are of no use

![Image](https://github.com/DeCenter-AI/decenterai-demo.streamlit.app/assets/131058062/51bad942-19fa-412a-97b9-e1189ec14b71)

- [x] Change these to "Demo V1" "Demo V2" "Demo V3"

**Comment by Nasfame** [comment]
@Dineshjnld build this app in this repo

**Comment by Dineshjnld** [comment]
completed 5 tasks 
remaining: 6th task and closing the side bar
