### ISSUE TITLE
Demo Sample Zip files

### ISSUE THREAD

**Issue by VictorKaycee17** [DeCenter-AI/decenterai-demo.streamlit#4]
Add the demo sample zip files to the side bar so they will be available for download by demo users.

**Comment by VictorKaycee17** [comment]
Also, use "Demo App V3" instead of "app" will do. Then you can remove the V1 and V2 from the side bar

**Comment by Dineshjnld** [comment]
![Image](https://github.com/DeCenter-AI/decenterai-demo.streamlit/assets/106725225/00e4d62d-6c25-4fa2-99d7-1fc729f660ab)
