### ISSUE TITLE
minimising the time (upload zip to training scripts)

### ISSUE THREAD

**Issue by VictorKaycee17** [DeCenter-AI/decenterai-demo.streamlit#7]
Please reduce the waiting time as much as possible

**Comment by VictorKaycee17** [comment]
What's the update on this task ?

**Comment by Dineshjnld** [comment]
will be updated by tonight

**Comment by VictorKaycee17** [comment]
Let me know when it's done so I can test it

**Comment by Nasfame** [comment]
Done merged in #8
